### ISSUE TITLE
How to make settings persistant?

### ISSUE THREAD

**Issue by Elespecia** [cncjs/cncjs#836]
#### Description

I'm sick of having to make all the settings every now and then, and everytime I redeploy the Docker-image (yes, I'm running the contianerversion).

I fail to see any file that I can bind with Docker but also have limited knowledge of you NPM and NodeJS work.

#### Versions

- CNCjs: All versions (Currently at 1.10.3)

#### How Do You Install CNCjs?

- [ ] NPM
- [ ] Download the CNCjs Desktop Application
- [X] Docker-compose

```
version: "3.7"
services:
  cncjs:
    container_name: CNCjs
    image: cncjs/cncjs:latest
    ports:
      - "8005:8000"
    volumes:
      - /docker/CNCjs:/cncjs
    network_mode: bridge
    hostname: cncjs
    restart: unless-stopped
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0

```
#### CNC Controller

- [x] Grbl
- [ ] Smoothieware
- [ ] TinyG/g2core

#### Hardware

- [ ] Raspberry Pi
- [X] Desktop or Laptop
- [ ] Mobile Device

#### Operating System

- [ ] Not Applicable
- [ ] Windows
- [ ] Mac
- [X] Linux

**Comment by thijstriemstra** [comment]
Good question; but I think it's a session/cookie thing, meaning it's only persisted in the browser. I'd love to be proven wrong though.

**Comment by Elespecia** [comment]
I think you're right.
That's not ideal with machine settings, macros and configurations.

**Comment by onezero1010101** [comment]
So I think I might have this fixed, try these volumes and see if that helps.  The .cncjs-sessions is a folder, .cncrc is a file.  You will need to create a blank file for the .cncrc, or it will create a folder

```
name: cncjs
services:
  cncjs:
    container_name: cnc
    image: cncjs/cncjs:latest
    privileged: true
    ports:
      - 80:8000
    volumes:
      - ./cncjs/.cncjs-sessions:/root/.cncjs-sessions
      - ./cncjs/.cncrc:/root/.cncrc

```
